package kuda

// LIST OF API SERVICES OFFERED BY KUDA
const (
	ADMIN_CREATE_VIRTUAL_ACCOUNT                ServiceType = "ADMIN_CREATE_VIRTUAL_ACCOUNT"
	ADMIN_UPDATE_VIRTUAL_ACCOUNT                ServiceType = "ADMIN_UPDATE_VIRTUAL_ACCOUNT"
	ADMIN_DISABLE_VIRTUAL_ACCOUNT               ServiceType = "ADMIN_DISABLE_VIRTUAL_ACCOUNT"
	ADMIN_ENABLE_VIRTUAL_ACCOUNT                ServiceType = "ADMIN_ENABLE_VIRTUAL_ACCOUNT"
	RETRIEVE_SINGLE_VIRTUAL_ACCOUNT             ServiceType = "ADMIN_RETRIEVE_SINGLE_VIRTUAL_ACCOUNT"
	BANK_LIST                                   ServiceType = "BANK_LIST"
	NAME_ENQUIRY                                ServiceType = "NAME_ENQUIRY"
	SINGLE_FUND_TRANSFER                        ServiceType = "SINGLE_FUND_TRANSFER"
	VIRTUAL_ACCOUNT_FUND_TRANSFER               ServiceType = "VIRTUAL_ACCOUNT_FUND_TRANSFER"
	TRANSACTION_STATUS_QUERY                    ServiceType = "TRANSACTION_STATUS_QUERY"
	RETRIEVE_VIRTUAL_ACCOUNT_BALANCE            ServiceType = "RETRIEVE_VIRTUAL_ACCOUNT_BALANCE"
	ADMIN_MAIN_ACCOUNT_TRANSACTIONS             ServiceType = "ADMIN_MAIN_ACCOUNT_TRANSACTIONS"
	ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS    ServiceType = "ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS"
	ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS          ServiceType = "ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS"
	ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS ServiceType = "ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS"
	FUND_VIRTUAL_ACCOUNT                        ServiceType = "FUND_VIRTUAL_ACCOUNT"
	WITHDRAW_VIRTUAL_ACCOUNT                    ServiceType = "WITHDRAW_VIRTUAL_ACCOUNT"
	ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE         ServiceType = "ADMIN_RETRIEVE_MAIN_ACCOUNT_BALANCE"
	RETRIEVE_TRANSACTION_LOGS                   ServiceType = "RETRIEVE_TRANSACTION_LOGS"

	//KUDA SAVING API
	RETRIEVE_SPEND_AND_SAVE_TRANSACTIONS ServiceType = "RETRIEVE_SPEND_AND_SAVE_TRANSACTIONS"
	CREATE_PLAIN_SAVINGS                 ServiceType = "CREATE_PLAIN_SAVINGS"
	GET_PLAIN_SAVINGS                    ServiceType = "GET_PLAIN_SAVINGS"
	CREATE_OPEN_FLEXIBLE_SAVE            ServiceType = "CREATE_OPEN_FLEXIBLE_SAVE"
	CREATE_CLOSED_FLEXIBLE_SAVE          ServiceType = "CREATE_CLOSED_FLEXIBLE_SAVE"
	GET_ALL_CUSTOMER_PLAIN_SAVINGS       ServiceType = "GET_ALL_CUSTOMER_PLAIN_SAVINGS"
	GET_ALL_PLAIN_SAVINGS                ServiceType = "GET_ALL_PLAIN_SAVINGS"
	UPDATE_PLAIN_SAVINGS                 ServiceType = "UPDATE_PLAIN_SAVINGS"
	PLAIN_SAVINGS_TRANSACTIONS           ServiceType = "PLAIN_SAVINGS_TRANSACTIONS"
	RETRIEVE_PLAIN_SAVINGS_TRANSACTIONS  ServiceType = "RETRIEVE_PLAIN_SAVINGS_TRANSACTIONS"

	//Kuda Bill Payment & Betting Services API
	GET_BILLERS_BY_TYPE       ServiceType = "GET_BILLERS_BY_TYPE"
	VERIFY_BILL_CUSTOMER      ServiceType = "VERIFY_BILL_CUSTOMER"
	ADMIN_PURCHASE_BILL       ServiceType = "ADMIN_PURCHASE_BILL"
	PURCHASE_BILL             ServiceType = "PURCHASE_BILL"
	BILL_TSQ                  ServiceType = "BILL_TSQ"
	ADMIN_GET_PURCHASED_BILLS ServiceType = "ADMIN_GET_PURCHASED_BILLS"
	GET_PURCHASED_BILLS       ServiceType = "GET_PURCHASED_BILLS"

	//GiftCards
	GET_GIFT_CARD       ServiceType = "GET_GIFT_CARD"
	ADMIN_BUY_GIFT_CARD ServiceType = "ADMIN_BUY_GIFT_CARD"
	BUY_GIFT_CARD       ServiceType = "BUY_GIFT_CARD"
	GIFT_CARD_TSQ       ServiceType = "GIFT_CARD_TSQ"

	//Kuda Cards
	REQUEST_CARD                  ServiceType = "REQUEST_CARD"
	GET_CUSTOMER_CARDS            ServiceType = "GET_CUSTOMER_CARDS"
	ACTIVATE_CARD                 ServiceType = "ACTIVATE_CARD"
	DEACTIVATE_CARD               ServiceType = "DEACTIVATE_CARD"
	MANAGE_CARD_TRANSACTION_LIMIT ServiceType = "MANAGE_CARD_TRANSACTION_LIMIT"
	MANAGE_CARD_CHANNEL           ServiceType = "MANAGE_CARD_CHANNEL"
	GET_CARD_PIN                  ServiceType = "GET_CARD_PIN"
	CHANGE_CARD_PIN               ServiceType = "CHANGE_CARD_PIN"
	BLOCK_CARD                    ServiceType = "BLOCK_CARD"
	UNBLOCK_CARD                  ServiceType = "UNBLOCK_CARD"
)
